// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_uC_FqKPSpFSmpYXcAg4gr-dQxOFbI0',
    appId: '1:1092230170530:android:f5eccb975604ccfb5a14fb',
    messagingSenderId: '1092230170530',
    projectId: 'ismmart-vms',
    databaseURL: 'https://ismmart-vms-default-rtdb.firebaseio.com',
    storageBucket: 'ismmart-vms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMrZPUF09uVAUhJGgZL2X-Afm3JS9EL-A',
    appId: '1:1092230170530:ios:326c9d865da37a205a14fb',
    messagingSenderId: '1092230170530',
    projectId: 'ismmart-vms',
    databaseURL: 'https://ismmart-vms-default-rtdb.firebaseio.com',
    storageBucket: 'ismmart-vms.appspot.com',
    androidClientId: '1092230170530-dqkto2vcauisc76v2pc61g73q462al1g.apps.googleusercontent.com',
    iosClientId: '1092230170530-qvg7isodscflmojqjusd0v6bhikacirh.apps.googleusercontent.com',
    iosBundleId: 'com.ismmart.ismmartVms',
  );
}
